version: "0.1"
services:
  taky-cot:
    image: skadakar/taky:unified
    container_name: taky-cot
    #   command:
      #- '--config.file=/etc/prometheus/prometheus.yml'
    user: "1000"
    ports:
            - 8087:8087
            - 8089:8089
    restart: unless-stopped
    environment:
     - mode=cot
     - public_ip=123.123.123.123
    volumes:
      - /root/data/:/data
  taky-data:
    image: skadakar/taky:unified
    container_name: taky-data
    #    command:
      #- '--config.file=/etc/prometheus/prometheus.yml'
    user: "1000"
    ports:
            - 8080:8080
    restart: unless-stopped
    environment:
     - mode=data
     - public_ip=123.123.123.123
    volumes:
      - /root/data/:/data
volumes:
        data:
